version: '3.8'

services:
  wall_forum:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wall_forum
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - uploads_data:/app/app/static/uploads
      - db_data:/app/instance
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=change_me_in_production
      - UPLOAD_FOLDER=/app/app/static/uploads
      - SQLALCHEMY_DATABASE_URI=sqlite:///forum.db
    command: >
      sh -c "python init_db.py && gunicorn --bind 0.0.0.0:5000 run:app"

volumes:
  uploads_data:
  db_data:
